---
title: "Tidy-data-and-relational-datasets"
author: "Yuxuan Du"
date: "2023-09-26"
output: html_document
---

```{r}
library(tidyverse)
library(tidyr)
options(tibble.print_min = 5)
```

## tidy data
```{r}
pulse_df = 
  haven::read_sas("./DATA/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    values_to = "bdi_score", 
    names_prefix = "bdi_score_"
  ) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m"), 
    visit = factor(visit)
  )

pulse_df
```
assessment 1
```{r}
litter_df = 
  read_csv("./DATA/FAS_litters.csv") |>
  janitor::clean_names() |>
  select(litter_number, gd0_weight, gd18_weight)|>
  pivot_longer(
    gd0_weight:gd18_weight, 
    names_to = "gd",
    values_to = "weight", 
    names_prefix = "gd"
  ) |>
  mutate(
    gd = case_match(
      gd, 
      "0_weight" ~ 0, 
      "18_weught" ~ 18, 
      )
  )

litter_df
```

## bind rows
import LoTR words data
```{r}
fellowship_df = 
  readxl::read_excel("DATA/LotR_words.xlsx", range = "B3:D6")|>
  mutate(movie = "fellowship")
towers_df = 
  readxl::read_excel("DATA/LotR_words.xlsx", range = "F3:H6")|>
  mutate(movie = "towers")
return_df = 
  readxl::read_excel("DATA/LotR_words.xlsx", range = "J3:L6")|>
  mutate(movie = "return")

lotr_df = 
  bind_rows(fellowship_df, towers_df, return_df)|>
  pivot_longer(
    Male:Female, 
    names_to = "gender", 
    values_to = "word"
  )|>
  relocate(movie)
```

## revisit FAS
```{r}
litters_df = 
  read_csv("DATA/FAS_litters.csv")|>
  janitor::clean_names()|>
  mutate(wt_gain = gd18_weight-gd0_weight)|>
  select(litter_number, group, wt_gain)|>
  separate(group, into = c("dose", "day_of_tx"), 3)

pups_df = 
  read_csv("DATA/FAS_pups.csv")|>
  janitor::clean_names()|>
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male", 
      2 ~ "felame"
    )
  )

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")
```